### PR TITLE
Hotfix CRAN: addresses #182: "caption" paragraph style is now handled by flextable…

### LINKED ISSUE #182: flextable revdepcheck
Hello @eanokian 

The fix for this issue ([commit d84e1d73](https://github.com/davidgohel/flextable/commit/d84e1d736e261924badfe062b8a115daff77a753)) introduced word_style into flextable's par_struct(). 

Before this change, calling `flextable::style(..., pr_p = officer::fp_par(word_style = "..."))` was silently ignored because flextable's internal paragraph structure had no word_style field — the value was simply dropped.

But junco new version does not let me deploy the fix, it causes a revdepcheck failure for flextable. junco applies a Word paragraph style to the title row of its tables:

```
pr_p = officer::fp_par(word_style = "Caption"))                                                                                                                                             ```
```

Before the fix, this call had no effect — the "Caption" value was silently discarded but now there is a fix it has an effect. "Caption" is the style_id, not the style_name — the actual style name in junco's template is "caption". This fails and officer raises:

```
Error: Some styles can not be found in the document: 'Caption'
```

Is it possible to fix your cran version so that I can deploy to CRAN ?

### sessionInfo()

```R
> sessionInfo()
R version 4.5.2 (2025-10-31)
Platform: aarch64-apple-darwin20
Running under: macOS Tahoe 26.2

Matrix products: default
BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib 
LAPACK: /Library/Frameworks/R.framework/Versions/4.5-arm64/Resources/lib/libRlapack.dylib;  LAPACK version 3.12.1

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

time zone: Europe/Paris
tzcode source: internal

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] rlistings_0.2.13  tibble_3.3.1      junco_0.1.3       rtables_0.6.15    magrittr_2.0.4    formatters_0.5.12

loaded via a namespace (and not attached):
 [1] xslt_1.5.1                 gtable_0.3.6               xfun_0.56                  ggplot2_4.0.1              lattice_0.22-7             rtables.officer_0.1.2.9000
 [7] vctrs_0.7.1                tools_4.5.2                Rdpack_2.6.5               generics_0.1.4             curl_7.0.0                 pkgconfig_2.0.3           
[13] katex_1.5.0                Matrix_1.7-4               data.table_1.18.2.1        checkmate_2.3.3            RColorBrewer_1.1-3         S7_0.2.1                  
[19] tidytlg_0.11.0             uuid_1.2-2                 readxl_1.4.5               assertthat_0.2.1           lifecycle_1.0.5            flextable_0.9.11          
[25] compiler_4.5.2             farver_2.1.2               stringr_1.6.0              textshaping_1.0.4          fontquiver_0.2.1           fontLiberation_0.1.0      
[31] htmltools_0.5.9            yaml_2.3.12                pillar_1.11.1              crayon_1.5.3               tidyr_1.3.2                openssl_2.3.4             
[37] tern_0.9.10                fontBitstreamVera_0.1.1    nestcolor_0.1.3            zip_2.3.3                  tidyselect_1.2.1           digest_0.6.39             
[43] stringi_1.8.7              dplyr_1.1.4                purrr_1.2.1                forcats_1.0.1              splines_4.5.2              fastmap_1.2.0             
[49] grid_4.5.2                 cli_3.6.5                  equatags_0.2.2             patchwork_1.3.2            survival_3.8-6             broom_1.0.12              
[55] huxtable_5.8.0             withr_3.0.2                gdtools_0.4.4              scales_1.4.0               backports_1.5.0            rmarkdown_2.30            
[61] officer_0.7.3              otel_0.2.0                 cellranger_1.1.0           askpass_1.2.1              ragg_1.5.0                 png_0.1-8                 
[67] evaluate_1.0.5             knitr_1.51                 rbibutils_2.4.1            V8_8.0.1                   rlang_1.1.7                Rcpp_1.1.1                
[73] glue_1.8.0                 xml2_1.5.2                 jsonlite_2.0.0             rstudioapi_0.18.0          R6_2.6.1                   systemfonts_1.3.1
```

### Relevant log output

```R
> knitr::purl("vignettes/table_and_listing_customizations.rmd")


processing file: vignettes/table_and_listing_customizations.rmd
                                                                                                                                                                                                                                         
output file: table_and_listing_customizations.R
[1] "table_and_listing_customizations.R"
> source("table_and_listing_customizations.R")
Loading required package: formatters

Attaching package: ‘formatters’

The following object is masked from ‘package:base’:

    %||%

Loading required package: rtables
Loading required package: magrittr

Attaching package: ‘rtables’

The following object is masked from ‘package:utils’:

    str

Registered S3 method overwritten by 'tern':
  method   from 
  tidy.glm broom
Loading required package: tibble
Error in convert_custom_styles_in_wml(xml_str, x$styles) : 
  Some styles can not be found in the document: 'Caption'
```

### PR DESCRIPTION
**Pull request by eanokian**
…, not by manipulating the XML; renamed function add_title_style_caption() to add_hanging_indent_in_title_XML()

# Pull Request

Fixes #182 
"caption" paragraph style in the docx exporter is now handled by flextable instead of manipulating the XML

## Checks

- [x] (Have you updated the changelog.md ?)

### CODE REVIEW

File: R/docx_exporter_functions.R [hunk 1]
```diff
@@ -316,7 +314,7 @@ insert_title_hanging_indent_v3 <- function(flx,
   )
   # nolint end
 
-  flx <- flextable::style(x = flx, part = "header", i = 1, pr_p = officer::fp_par(word_style = "Caption"))
+  flx <- flextable::style(x = flx, part = "header", i = 1, pr_p = officer::fp_par(word_style = "caption"))
```
Comment (davidgohel) [inline R/docx_exporter_functions.R:317]: Not sure it's relevant (maybe you did it) but I would make sure this style exists and if not use `officer::docx_set_paragraph_style()` to create it.

Comment (eanokian) [reply R/docx_exporter_functions.R:317]: the style exists in the template docx file as "Caption" with capital "C" but if I comment out/remove that line of code then style is reset to "Normal" so I think it's fine as it is.
